server:
  port: 8098

spring:

  profiles.active: @activatedProperties@

  liquibase:
    change-log: classpath:db/changelog/migrations.xml
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}/${db.database}?stringtype=unspecified
    username: ${db.username}
    password: ${db.password}

  jackson:
    serialization:
      indent_output: true

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha