@startuml database
left to right direction

hide circle
skinparam linetype ortho

entity "books" as books {
  *id : INT <<generated>>
  --
  * title: VARCHAR(255)
  description: VARCHAR(255)
  * author: VARCHAR(255) 
  rating: VARCHAR(31)
  rating_count: VARCHAR(15)
  reg_price: VARCHAR(15)
  audio_len: VARCHAR(31)
  language: VARCHAR(31)
  page_URL: VARCHAR(1023)
  image_URL: VARCHAR(1023)
}

entity "wish_lists" as wls {
    * id : INT <<generated>>
    --
    * book_id: INT <<FK>>
}

books ||--o{ wls

@enduml